### ISSUE TITLE
The plug-in cannot be opened

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [MarcinMoskala/AnkiMarkdown-obsidian#2]
There is a problem with the plug-in. It cannot be opened in the latest version of obsidian. I hope it can be fixed (I translated it into English)

**Comment by shoudeyunkaijianyueming** [comment]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/71814666/183682091-b4a18bad-b66c-4287-b119-0062acb902de.png">

**Comment by MarcinMoskala** [comment]
Thank you for your interest, but the plugin is not released yet. This is likely why you cannot load it. I will share it with others once its API gets stable.
